kind: pipeline
type: docker
name: Build_and_publish

steps:
  - name: build_docker_image
    image: node:18-slim
    when:
      branch:
        - main
      event:
        - push
  
    commands:
      - ls
