kind: pipeline
type: docker
name: Build_and_publish

steps:
  - name: build_docker_image
    image: node:18-slim
    when:
      branch:
        - main
      event:
        - push
  
    commands:
      - docker build --platform linux/amd64 --rm=false -f ./images/Dockerfile -t shane-bt-test .
