kind: pipeline
type: docker
name: Build_and_publish

depends_on:
  - test

steps:
  - name: build_docker_image
    image: node:16-slim
    when:
      branch:
        - main
      event:
        - push
  
    commands:
      - docker build --platform linux/amd64 --rm=false -f ./images/Dockerfile -t shane-bt-test .
    
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
